---
title: "Analysing Helipad Data"
author: "Danny Wong"
date: "Sunday, April 05, 2015"
output: html_document
---

We have some data from the KSS HEMS patients conveyed to KCH.

```{r}
#Read the data into a dataframe, specify the NA strings to incorporate the missing values
data <- read.csv("data/HEMSdata.csv", na.strings=c("NA","n/a", ""))

#Let's look at the table
View(data)

#Let's see how many cases there are
print(nrow(data))
```

Notice that the coordinates are in the Ordnance Survey Grid format under the column "Grid". For us to work with this meaningfully, we need to convert this to latitude and longitude (WGS84) coordinates.

Fortunately there are others who have encountered the same problem before:

Sources: 
  -http://stackoverflow.com/questions/23017053/how-to-convert-uk-grid-reference-to-latitude-and-longitude-in-r
  -https://stat.ethz.ch/pipermail/r-sig-geo/2010-November/010141.html
  -http://www.hannahfry.co.uk/blog/2012/02/01/converting-british-national-grid-to-latitude-and-longitude-ii
  -http://cran.r-project.org/web/packages/rnrfa/rnrfa.pdf

```{r}
#Load the required packages
require(rnrfa)
require(dplyr)

#Parse the OS Grid References into Eastings and Northings
EN <- OSGParse(data$Grid)

#Add these onto the data
data <- mutate(data, Eastings = EN$Easting, Northings = EN$Northing)

#Write to .csv
write.csv(data, file="data/cleaned.csv")
```

